# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    ruby: 'puppetlabs/ruby'
    stdlib: 'puppetlabs/stdlib'
  repositories:
    bundler:
      repo: 'https://github.com/puppetlabs-operations/puppet-bundler.git'
      ref: 'a7eba21a471016123effe728c2db3602feaffb13'
    rack:
      repo: 'https://github.com/puppetlabs-operations/puppet-rack.git'
      ref: '19f1e613a82d0aa1fbbf6b3b1ff874cf0fdbd707'
